version: "3"
services:
  primary:
    container_name: primary
    image: postgres10
    build: postgres/
    environment:
      REPLICATION_ROLE: primary
    ports:
      - 5432:5432

  standby1:
    container_name: standby1
    image: postgres10
    build: postgres/
    environment:
      REPLICATION_ROLE: standby1
      REPLICATION_NAME: standby1
    ports:
      - 5433:5432

  standby2:
    container_name: standby2
    image: postgres10
    build: postgres/
    environment:
      REPLICATION_ROLE: standby
      REPLICATION_NAME: standby2
    ports:
      - 5434:5432

